fail_fast: true
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [-l 88, --preview]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
