version: '3.1'

services:
  web:
    image: nginx
    volumes:
    - ./infrastructure/nginx:/etc/nginx/conf.d
    - ./static:/var/www/admin/static
    ports:
    - "8080:80"

  admin:
    build:
      context: .
    image: admin
    restart: always
    env_file:
      - .env.docker

  mongo-db:
    image: mongo
    restart: always
    env_file:
      - .env.docker

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017/
